module.exports = [{
    "Andijan": [
        "Andijan", "Asaka", "Baliqchi", "Boz", "Buloqboshi", "Izboskan", "Jalalkuduk", "Khodjaobod", "Kurgontepa", "Kurgontepa", "Marhamat", "Oltinkol", "Pakhtaabad", "Shakhrikhan", "Ulugnor"
    ],
    "Fergana": [
        "Altyariq",
        "Baghdad",
        "Beshariq",
        "Ibrat",
        "Dangara",
        "Vadil",
        "Navbakhor",
        "Langar",
        "Quva",
        "Rishton",
        "Ravan",
        "Tashlaq",
        "Uchkuprik",
        "Yaypan",
        "Yozyovon"
    ],
    "Namangan": ["Chartak",
        "Chust",
        "Kasansay",
        "Jumashuy",
        "Tashbulak",
        "Khakkulabad",
        "Pap",
        "Turakurgan",
        "Uchkurgan",
        "Uychi",
        "Yangikurgan",
    ],
    "Tashkent": ["Zafar",
        "Gazalkent",
        "Buka",
        "Chinaz",
        "Qibray",
        "Okhangaron",
        "Oqqurgan",
        "Parkent",
        "Piskent",
        "Dustobod",
        "Keles",
        "Toytepa",
        "Gulbakhor",
        "Yangibozor",
        "Bektemir",
        "Chilanzar",
        "Yashnobod",
        "Mirobod",
        "Mirzo Ulugbek",
        "Sergeli",
        "Shaykhontohur",
        "Olmazar",
        "Uchtepa",
        "Yakkasaray",
        "Yunusabad",
    ],
    "Sirdaryo": ["Sardoba",
        "Bayaut",
        "Dehkonobod",
        "Khavast",
        "Navruz",
        "Saikhun",
        "Pakhtaabad",
        "Sirdaryo",
    ],
    "Jizzakh": ["Goliblar",
        "Usmat",
        "Dustlik",
        "Yangikishlok",
        "Gallorol",
        "Uchtepa",
        "Gagarin",
        "Pakhtakor",
        "Balandchakir",
        "Zaamin",
        "Zafarobod",
        "Zarbdar",
    ],
    "Surkhandaryo": ["Angor",
        "Bandixon",
        "Boysun",
        "Denau",
        "Jarkurghon",
        "Sariq",
        "Kumkurghon",
        "Khalkobod (Khalkabad)",
        "Qarluq",
        "Sariosiyo",
        "Sherobod (Shirabad)",
        "Shurchi",
        "Uchkhizil",
        "Uzun",
    ],
    "Qashqadaryo": [
        "Chirakchi",
        "Karashina",
        "Guzar",
        "Kamashi",
        "Beshkent",
        "Koson",
        "Muglan",
        "Kitab",
        "Yangi-Mirishkor",
        "Muborak",
        "Yangi-Nishon",
        "Shahrisabz",
        "Yakkabog",
    ],
    "Samarkand": ["Bulungur",
        "Ishtikhon",
        "Jomboy",
        "Paishanba",
        "Koshrabot",
        "Oqtosh",
        "Nurobod",
        "Laish",
        "Ziadin",
        "Payariq",
        "Juma",
        "Gulabad",
        "Toyloq",
        "Urgut",
    ],
    "Bukhara": ["Alat",
        "Galaasiya",
        "Gijduvan",
        "Jondor",
        "Kagan",
        "Qorako'l",
        "Karaulbazar",
        "Yangibazar",
        "Romitan",
        "Shafirkan",
        "Vabkent",
    ],
    "Navoiy": ["Kanimekh",
        "Karmana",
        "Kyzyltepa",
        "Yangirabad",
        "Beshrabot",
        "Nurata",
        "Tamdibulok",
        "Uchkuduk",
    ],
    "Xorazm": ["Bog'ot",
        "Gurlen",
        "Xonqa",
        "Hazorasp",
        "Khiva",
        "Qo'shko'pir",
        "Shovot",
        "Qorovul",
        "Yangiariq",
        "Yangibozor",
    ],
    "Karakalpakstan": [
        "Mang'it",
        "Beruniy",
        "Chimboy",
        "Bo'ston",
        "Kegeyli",
        "Mo'ynoq",
        "Oqmang'it",
        "Qanliko'l",
        "Qo'ng'irot",
        "Qorao'zak",
        "Shumanay",
        "Taxtako'pir",
        "To'rtko'l",
        "Xo'jayli",
    ]
}]